CREATE TABLE employees {
    employeesId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    Nom VARCHAR(25) NOT NULL,
    Prénom VARCHAR(25) NOT NULL,
    Adresse VARCHAR(25) NOT NULL,
    Numéro de sécurité sociale VARCHAR(10) NOT NULL,
    Date embauche DATE NOT NULL,
    Poste occupée VARCHAR(50) NOT NULL,
    Départements VARCHAR(50) NOT NULL,
    Salaire de base INTEGER NOT NULL,
    Heures supplémentaire INTEGER NOT NULL,
    Avantages sociaux VARCHAR(100) NOT NULL,
    Retenues impôts INTEGER NOT NULL,
    Heures Travaillées INTEGER NOT NULL,
    Congés pris INTEGER NOT NULL,
    Absences INTEGER NOT NULL,
    Cours suivi VARCHAR(100) NOT NULL,
    Certifications obtenues VARCHAR(100) NOT NULL,
    Objectifs de performance VARCHAR(100) NOT NULL,
    Commentaires gestionnaires VARCHAR(100) NOT NULL,
}