insert into Poste (idPoste, label, idDepartement) values (1, 'Food Chemist', 1);
insert into Poste (idPoste, label, idDepartement) values (2, 'Marketing Manager', 2);
insert into Poste (idPoste, label, idDepartement) values (3, 'Senior Developer', 3);
insert into Poste (idPoste, label, idDepartement) values (4, 'Help Desk Operator', 4);
insert into Poste (idPoste, label, idDepartement) values (5, 'Structural Analysis Engineer', 5);
insert into Poste (idPoste, label, idDepartement) values (6, 'Assistant Media Planner', 6);
insert into Poste (idPoste, label, idDepartement) values (7, 'Recruiting Manager', 7);
insert into Poste (idPoste, label, idDepartement) values (8, 'Computer Systems Analyst III', 8);
insert into Poste (idPoste, label, idDepartement) values (9, 'Safety Technician III', 9);
insert into Poste (idPoste, label, idDepartement) values (10, 'Assistant Professor', 10);
insert into Poste (idPoste, label, idDepartement) values (11, 'Accountant IV', 11);
insert into Poste (idPoste, label, idDepartement) values (12, 'Financial Analyst', 12);
insert into Poste (idPoste, label, idDepartement) values (13, 'Developer I', 13);
insert into Poste (idPoste, label, idDepartement) values (14, 'Help Desk Operator', 14);
insert into Poste (idPoste, label, idDepartement) values (15, 'Marketing Assistant', 15);
insert into Poste (idPoste, label, idDepartement) values (16, 'Dental Hygienist', 16);
insert into Poste (idPoste, label, idDepartement) values (17, 'Senior Quality Engineer', 17);
insert into Poste (idPoste, label, idDepartement) values (18, 'VP Accounting', 18);
insert into Poste (idPoste, label, idDepartement) values (19, 'Systems Administrator IV', 19);
insert into Poste (idPoste, label, idDepartement) values (20, 'Social Worker', 20);
insert into Poste (idPoste, label, idDepartement) values (21, 'Recruiter', 21);
insert into Poste (idPoste, label, idDepartement) values (22, 'Safety Technician II', 22);
insert into Poste (idPoste, label, idDepartement) values (23, 'Recruiting Manager', 23);
insert into Poste (idPoste, label, idDepartement) values (24, 'Financial Analyst', 24);
insert into Poste (idPoste, label, idDepartement) values (25, 'Information Systems Manager', 25);
insert into Poste (idPoste, label, idDepartement) values (26, 'Graphic Designer', 26);
insert into Poste (idPoste, label, idDepartement) values (27, 'Sales Representative', 27);
insert into Poste (idPoste, label, idDepartement) values (28, 'Environmental Specialist', 28);
insert into Poste (idPoste, label, idDepartement) values (29, 'Mechanical Systems Engineer', 29);
insert into Poste (idPoste, label, idDepartement) values (30, 'Data Coordiator', 30);
insert into Poste (idPoste, label, idDepartement) values (31, 'Research Nurse', 31);
insert into Poste (idPoste, label, idDepartement) values (32, 'Teacher', 32);
insert into Poste (idPoste, label, idDepartement) values (33, 'Nurse', 33);
insert into Poste (idPoste, label, idDepartement) values (34, 'Executive Secretary', 34);
insert into Poste (idPoste, label, idDepartement) values (35, 'Paralegal', 35);
insert into Poste (idPoste, label, idDepartement) values (36, 'Senior Editor', 36);
insert into Poste (idPoste, label, idDepartement) values (37, 'Health Coach II', 37);
insert into Poste (idPoste, label, idDepartement) values (38, 'Accounting Assistant III', 38);
insert into Poste (idPoste, label, idDepartement) values (39, 'VP Sales', 39);
insert into Poste (idPoste, label, idDepartement) values (40, 'Office Assistant III', 40);
insert into Poste (idPoste, label, idDepartement) values (41, 'Librarian', 41);
insert into Poste (idPoste, label, idDepartement) values (42, 'Food Chemist', 42);
insert into Poste (idPoste, label, idDepartement) values (43, 'Internal Auditor', 43);
insert into Poste (idPoste, label, idDepartement) values (44, 'General Manager', 44);
insert into Poste (idPoste, label, idDepartement) values (45, 'Recruiting Manager', 45);
insert into Poste (idPoste, label, idDepartement) values (46, 'Senior Developer', 46);
insert into Poste (idPoste, label, idDepartement) values (47, 'Geological Engineer', 47);
insert into Poste (idPoste, label, idDepartement) values (48, 'Project Manager', 48);
insert into Poste (idPoste, label, idDepartement) values (49, 'Dental Hygienist', 49);
insert into Poste (idPoste, label, idDepartement) values (50, 'Structural Engineer', 50);
insert into Poste (idPoste, label, idDepartement) values (51, 'Assistant Manager', 51);
insert into Poste (idPoste, label, idDepartement) values (52, 'Senior Developer', 52);
insert into Poste (idPoste, label, idDepartement) values (53, 'Senior Editor', 53);
insert into Poste (idPoste, label, idDepartement) values (54, 'Accounting Assistant I', 54);
insert into Poste (idPoste, label, idDepartement) values (55, 'Environmental Specialist', 55);
insert into Poste (idPoste, label, idDepartement) values (56, 'Graphic Designer', 56);
insert into Poste (idPoste, label, idDepartement) values (57, 'Senior Developer', 57);
insert into Poste (idPoste, label, idDepartement) values (58, 'Chief Design Engineer', 58);
insert into Poste (idPoste, label, idDepartement) values (59, 'VP Sales', 59);
insert into Poste (idPoste, label, idDepartement) values (60, 'Editor', 60);
insert into Poste (idPoste, label, idDepartement) values (61, 'Administrative Assistant III', 61);
insert into Poste (idPoste, label, idDepartement) values (62, 'Editor', 62);
insert into Poste (idPoste, label, idDepartement) values (63, 'Dental Hygienist', 63);
insert into Poste (idPoste, label, idDepartement) values (64, 'Quality Engineer', 64);
insert into Poste (idPoste, label, idDepartement) values (65, 'Programmer Analyst IV', 65);
insert into Poste (idPoste, label, idDepartement) values (66, 'Structural Engineer', 66);
insert into Poste (idPoste, label, idDepartement) values (67, 'Environmental Tech', 67);
insert into Poste (idPoste, label, idDepartement) values (68, 'Human Resources Assistant I', 68);
insert into Poste (idPoste, label, idDepartement) values (69, 'VP Accounting', 69);
insert into Poste (idPoste, label, idDepartement) values (70, 'Senior Editor', 70);
insert into Poste (idPoste, label, idDepartement) values (71, 'Developer III', 71);
insert into Poste (idPoste, label, idDepartement) values (72, 'Dental Hygienist', 72);
insert into Poste (idPoste, label, idDepartement) values (73, 'Geological Engineer', 73);
insert into Poste (idPoste, label, idDepartement) values (74, 'Help Desk Technician', 74);
insert into Poste (idPoste, label, idDepartement) values (75, 'VP Sales', 75);
insert into Poste (idPoste, label, idDepartement) values (76, 'Speech Pathologist', 76);
insert into Poste (idPoste, label, idDepartement) values (77, 'Project Manager', 77);
insert into Poste (idPoste, label, idDepartement) values (78, 'General Manager', 78);
insert into Poste (idPoste, label, idDepartement) values (79, 'Automation Specialist IV', 79);
insert into Poste (idPoste, label, idDepartement) values (80, 'Accounting Assistant IV', 80);
insert into Poste (idPoste, label, idDepartement) values (81, 'Legal Assistant', 81);
insert into Poste (idPoste, label, idDepartement) values (82, 'Information Systems Manager', 82);
insert into Poste (idPoste, label, idDepartement) values (83, 'Editor', 83);
insert into Poste (idPoste, label, idDepartement) values (84, 'VP Marketing', 84);
insert into Poste (idPoste, label, idDepartement) values (85, 'Structural Engineer', 85);
insert into Poste (idPoste, label, idDepartement) values (86, 'Recruiting Manager', 86);
insert into Poste (idPoste, label, idDepartement) values (87, 'Chief Design Engineer', 87);
insert into Poste (idPoste, label, idDepartement) values (88, 'Office Assistant I', 88);
insert into Poste (idPoste, label, idDepartement) values (89, 'Geological Engineer', 89);
insert into Poste (idPoste, label, idDepartement) values (90, 'Teacher', 90);
insert into Poste (idPoste, label, idDepartement) values (91, 'VP Quality Control', 91);
insert into Poste (idPoste, label, idDepartement) values (92, 'Senior Financial Analyst', 92);
insert into Poste (idPoste, label, idDepartement) values (93, 'Sales Representative', 93);
insert into Poste (idPoste, label, idDepartement) values (94, 'Accountant IV', 94);
insert into Poste (idPoste, label, idDepartement) values (95, 'Media Manager II', 95);
insert into Poste (idPoste, label, idDepartement) values (96, 'Tax Accountant', 96);
insert into Poste (idPoste, label, idDepartement) values (97, 'Automation Specialist IV', 97);
insert into Poste (idPoste, label, idDepartement) values (98, 'Assistant Professor', 98);
insert into Poste (idPoste, label, idDepartement) values (99, 'Speech Pathologist', 99);
insert into Poste (idPoste, label, idDepartement) values (100, 'Developer IV', 100);
insert into Poste (idPoste, label, idDepartement) values (101, 'Editor', 101);
insert into Poste (idPoste, label, idDepartement) values (102, 'Programmer I', 102);
insert into Poste (idPoste, label, idDepartement) values (103, 'Staff Scientist', 103);
insert into Poste (idPoste, label, idDepartement) values (104, 'Account Representative II', 104);
insert into Poste (idPoste, label, idDepartement) values (105, 'Safety Technician I', 105);
insert into Poste (idPoste, label, idDepartement) values (106, 'Sales Representative', 106);
insert into Poste (idPoste, label, idDepartement) values (107, 'Actuary', 107);
insert into Poste (idPoste, label, idDepartement) values (108, 'Nuclear Power Engineer', 108);
insert into Poste (idPoste, label, idDepartement) values (109, 'Occupational Therapist', 109);
insert into Poste (idPoste, label, idDepartement) values (110, 'Legal Assistant', 110);
insert into Poste (idPoste, label, idDepartement) values (111, 'Paralegal', 111);
insert into Poste (idPoste, label, idDepartement) values (112, 'General Manager', 112);
insert into Poste (idPoste, label, idDepartement) values (113, 'Quality Control Specialist', 113);
insert into Poste (idPoste, label, idDepartement) values (114, 'Civil Engineer', 114);
insert into Poste (idPoste, label, idDepartement) values (115, 'Information Systems Manager', 115);
insert into Poste (idPoste, label, idDepartement) values (116, 'Database Administrator II', 116);
insert into Poste (idPoste, label, idDepartement) values (117, 'Physical Therapy Assistant', 117);
insert into Poste (idPoste, label, idDepartement) values (118, 'Administrative Officer', 118);
insert into Poste (idPoste, label, idDepartement) values (119, 'Product Engineer', 119);
insert into Poste (idPoste, label, idDepartement) values (120, 'Business Systems Development Analyst', 120);
insert into Poste (idPoste, label, idDepartement) values (121, 'Staff Scientist', 121);
insert into Poste (idPoste, label, idDepartement) values (122, 'Librarian', 122);
insert into Poste (idPoste, label, idDepartement) values (123, 'Chemical Engineer', 123);
insert into Poste (idPoste, label, idDepartement) values (124, 'Payment Adjustment Coordinator', 124);
insert into Poste (idPoste, label, idDepartement) values (125, 'Staff Scientist', 125);
insert into Poste (idPoste, label, idDepartement) values (126, 'Accounting Assistant II', 126);
insert into Poste (idPoste, label, idDepartement) values (127, 'Recruiter', 127);
insert into Poste (idPoste, label, idDepartement) values (128, 'Mechanical Systems Engineer', 128);
insert into Poste (idPoste, label, idDepartement) values (129, 'Chemical Engineer', 129);
insert into Poste (idPoste, label, idDepartement) values (130, 'Sales Associate', 130);
insert into Poste (idPoste, label, idDepartement) values (131, 'Internal Auditor', 131);
insert into Poste (idPoste, label, idDepartement) values (132, 'Marketing Assistant', 132);
insert into Poste (idPoste, label, idDepartement) values (133, 'Sales Associate', 133);
insert into Poste (idPoste, label, idDepartement) values (134, 'Payment Adjustment Coordinator', 134);
insert into Poste (idPoste, label, idDepartement) values (135, 'Programmer Analyst I', 135);
insert into Poste (idPoste, label, idDepartement) values (136, 'Software Consultant', 136);
insert into Poste (idPoste, label, idDepartement) values (137, 'VP Product Management', 137);
insert into Poste (idPoste, label, idDepartement) values (138, 'Marketing Manager', 138);
insert into Poste (idPoste, label, idDepartement) values (139, 'Paralegal', 139);
insert into Poste (idPoste, label, idDepartement) values (140, 'Social Worker', 140);
insert into Poste (idPoste, label, idDepartement) values (141, 'Food Chemist', 141);
insert into Poste (idPoste, label, idDepartement) values (142, 'Developer IV', 142);
insert into Poste (idPoste, label, idDepartement) values (143, 'Accountant III', 143);
insert into Poste (idPoste, label, idDepartement) values (144, 'Structural Engineer', 144);
insert into Poste (idPoste, label, idDepartement) values (145, 'Product Engineer', 145);
insert into Poste (idPoste, label, idDepartement) values (146, 'Business Systems Development Analyst', 146);
insert into Poste (idPoste, label, idDepartement) values (147, 'Analyst Programmer', 147);
insert into Poste (idPoste, label, idDepartement) values (148, 'Engineer IV', 148);
insert into Poste (idPoste, label, idDepartement) values (149, 'Analyst Programmer', 149);
insert into Poste (idPoste, label, idDepartement) values (150, 'Environmental Specialist', 150);
insert into Poste (idPoste, label, idDepartement) values (151, 'Registered Nurse', 151);
insert into Poste (idPoste, label, idDepartement) values (152, 'Research Associate', 152);
insert into Poste (idPoste, label, idDepartement) values (153, 'Business Systems Development Analyst', 153);
insert into Poste (idPoste, label, idDepartement) values (154, 'Information Systems Manager', 154);
insert into Poste (idPoste, label, idDepartement) values (155, 'Tax Accountant', 155);
insert into Poste (idPoste, label, idDepartement) values (156, 'Librarian', 156);
insert into Poste (idPoste, label, idDepartement) values (157, 'Financial Advisor', 157);
insert into Poste (idPoste, label, idDepartement) values (158, 'Staff Scientist', 158);
insert into Poste (idPoste, label, idDepartement) values (159, 'Associate Professor', 159);
insert into Poste (idPoste, label, idDepartement) values (160, 'Safety Technician III', 160);
insert into Poste (idPoste, label, idDepartement) values (161, 'Sales Associate', 161);
insert into Poste (idPoste, label, idDepartement) values (162, 'Accountant III', 162);
insert into Poste (idPoste, label, idDepartement) values (163, 'Junior Executive', 163);
insert into Poste (idPoste, label, idDepartement) values (164, 'Marketing Assistant', 164);
insert into Poste (idPoste, label, idDepartement) values (165, 'Help Desk Technician', 165);
insert into Poste (idPoste, label, idDepartement) values (166, 'Accounting Assistant I', 166);
insert into Poste (idPoste, label, idDepartement) values (167, 'Biostatistician III', 167);
insert into Poste (idPoste, label, idDepartement) values (168, 'Nuclear Power Engineer', 168);
insert into Poste (idPoste, label, idDepartement) values (169, 'Human Resources Assistant III', 169);
insert into Poste (idPoste, label, idDepartement) values (170, 'Structural Analysis Engineer', 170);
insert into Poste (idPoste, label, idDepartement) values (171, 'Assistant Professor', 171);
insert into Poste (idPoste, label, idDepartement) values (172, 'General Manager', 172);
insert into Poste (idPoste, label, idDepartement) values (173, 'Compensation Analyst', 173);
insert into Poste (idPoste, label, idDepartement) values (174, 'Registered Nurse', 174);
insert into Poste (idPoste, label, idDepartement) values (175, 'Electrical Engineer', 175);
insert into Poste (idPoste, label, idDepartement) values (176, 'Systems Administrator III', 176);
insert into Poste (idPoste, label, idDepartement) values (177, 'Project Manager', 177);
insert into Poste (idPoste, label, idDepartement) values (178, 'VP Accounting', 178);
insert into Poste (idPoste, label, idDepartement) values (179, 'Systems Administrator III', 179);
insert into Poste (idPoste, label, idDepartement) values (180, 'Information Systems Manager', 180);
insert into Poste (idPoste, label, idDepartement) values (181, 'Speech Pathologist', 181);
insert into Poste (idPoste, label, idDepartement) values (182, 'Information Systems Manager', 182);
insert into Poste (idPoste, label, idDepartement) values (183, 'Staff Scientist', 183);
insert into Poste (idPoste, label, idDepartement) values (184, 'Speech Pathologist', 184);
insert into Poste (idPoste, label, idDepartement) values (185, 'Assistant Media Planner', 185);
insert into Poste (idPoste, label, idDepartement) values (186, 'Nuclear Power Engineer', 186);
insert into Poste (idPoste, label, idDepartement) values (187, 'Senior Editor', 187);
insert into Poste (idPoste, label, idDepartement) values (188, 'Account Coordinator', 188);
insert into Poste (idPoste, label, idDepartement) values (189, 'Senior Editor', 189);
insert into Poste (idPoste, label, idDepartement) values (190, 'Business Systems Development Analyst', 190);
insert into Poste (idPoste, label, idDepartement) values (191, 'Marketing Manager', 191);
insert into Poste (idPoste, label, idDepartement) values (192, 'Assistant Media Planner', 192);
insert into Poste (idPoste, label, idDepartement) values (193, 'Tax Accountant', 193);
insert into Poste (idPoste, label, idDepartement) values (194, 'Research Nurse', 194);
insert into Poste (idPoste, label, idDepartement) values (195, 'Budget/Accounting Analyst III', 195);
insert into Poste (idPoste, label, idDepartement) values (196, 'Senior Sales Associate', 196);
insert into Poste (idPoste, label, idDepartement) values (197, 'Help Desk Operator', 197);
insert into Poste (idPoste, label, idDepartement) values (198, 'Office Assistant III', 198);
insert into Poste (idPoste, label, idDepartement) values (199, 'Cost Accountant', 199);
insert into Poste (idPoste, label, idDepartement) values (200, 'Professor', 200);
insert into Poste (idPoste, label, idDepartement) values (201, 'Automation Specialist I', 201);
insert into Poste (idPoste, label, idDepartement) values (202, 'Geological Engineer', 202);
insert into Poste (idPoste, label, idDepartement) values (203, 'Marketing Assistant', 203);
insert into Poste (idPoste, label, idDepartement) values (204, 'General Manager', 204);
insert into Poste (idPoste, label, idDepartement) values (205, 'VP Product Management', 205);
insert into Poste (idPoste, label, idDepartement) values (206, 'Community Outreach Specialist', 206);
insert into Poste (idPoste, label, idDepartement) values (207, 'Research Nurse', 207);
insert into Poste (idPoste, label, idDepartement) values (208, 'VP Marketing', 208);
insert into Poste (idPoste, label, idDepartement) values (209, 'Budget/Accounting Analyst IV', 209);
insert into Poste (idPoste, label, idDepartement) values (210, 'Media Manager II', 210);
insert into Poste (idPoste, label, idDepartement) values (211, 'Internal Auditor', 211);
insert into Poste (idPoste, label, idDepartement) values (212, 'Speech Pathologist', 212);
insert into Poste (idPoste, label, idDepartement) values (213, 'Analog Circuit Design manager', 213);
insert into Poste (idPoste, label, idDepartement) values (214, 'Administrative Assistant I', 214);
insert into Poste (idPoste, label, idDepartement) values (215, 'Technical Writer', 215);
insert into Poste (idPoste, label, idDepartement) values (216, 'Civil Engineer', 216);
insert into Poste (idPoste, label, idDepartement) values (217, 'Graphic Designer', 217);
insert into Poste (idPoste, label, idDepartement) values (218, 'Structural Engineer', 218);
insert into Poste (idPoste, label, idDepartement) values (219, 'Recruiter', 219);
insert into Poste (idPoste, label, idDepartement) values (220, 'Analog Circuit Design manager', 220);
insert into Poste (idPoste, label, idDepartement) values (221, 'Media Manager III', 221);
insert into Poste (idPoste, label, idDepartement) values (222, 'Professor', 222);
insert into Poste (idPoste, label, idDepartement) values (223, 'Systems Administrator II', 223);
insert into Poste (idPoste, label, idDepartement) values (224, 'GIS Technical Architect', 224);
insert into Poste (idPoste, label, idDepartement) values (225, 'Research Associate', 225);
insert into Poste (idPoste, label, idDepartement) values (226, 'Help Desk Technician', 226);
insert into Poste (idPoste, label, idDepartement) values (227, 'Chemical Engineer', 227);
insert into Poste (idPoste, label, idDepartement) values (228, 'Mechanical Systems Engineer', 228);
insert into Poste (idPoste, label, idDepartement) values (229, 'Human Resources Assistant III', 229);
insert into Poste (idPoste, label, idDepartement) values (230, 'Editor', 230);
insert into Poste (idPoste, label, idDepartement) values (231, 'Cost Accountant', 231);
insert into Poste (idPoste, label, idDepartement) values (232, 'Compensation Analyst', 232);
insert into Poste (idPoste, label, idDepartement) values (233, 'Automation Specialist III', 233);
insert into Poste (idPoste, label, idDepartement) values (234, 'Executive Secretary', 234);
insert into Poste (idPoste, label, idDepartement) values (235, 'Associate Professor', 235);
insert into Poste (idPoste, label, idDepartement) values (236, 'Office Assistant III', 236);
insert into Poste (idPoste, label, idDepartement) values (237, 'Financial Advisor', 237);
insert into Poste (idPoste, label, idDepartement) values (238, 'Research Assistant IV', 238);
insert into Poste (idPoste, label, idDepartement) values (239, 'Project Manager', 239);
insert into Poste (idPoste, label, idDepartement) values (240, 'Environmental Tech', 240);
insert into Poste (idPoste, label, idDepartement) values (241, 'Social Worker', 241);
insert into Poste (idPoste, label, idDepartement) values (242, 'Senior Quality Engineer', 242);
insert into Poste (idPoste, label, idDepartement) values (243, 'Internal Auditor', 243);
insert into Poste (idPoste, label, idDepartement) values (244, 'Geological Engineer', 244);
insert into Poste (idPoste, label, idDepartement) values (245, 'Human Resources Manager', 245);
insert into Poste (idPoste, label, idDepartement) values (246, 'Clinical Specialist', 246);
insert into Poste (idPoste, label, idDepartement) values (247, 'VP Accounting', 247);
insert into Poste (idPoste, label, idDepartement) values (248, 'Systems Administrator III', 248);
insert into Poste (idPoste, label, idDepartement) values (249, 'VP Product Management', 249);
insert into Poste (idPoste, label, idDepartement) values (250, 'Assistant Media Planner', 250);
insert into Poste (idPoste, label, idDepartement) values (251, 'Registered Nurse', 251);
insert into Poste (idPoste, label, idDepartement) values (252, 'Associate Professor', 252);
insert into Poste (idPoste, label, idDepartement) values (253, 'Speech Pathologist', 253);
insert into Poste (idPoste, label, idDepartement) values (254, 'Web Designer I', 254);
insert into Poste (idPoste, label, idDepartement) values (255, 'Tax Accountant', 255);
insert into Poste (idPoste, label, idDepartement) values (256, 'Senior Quality Engineer', 256);
insert into Poste (idPoste, label, idDepartement) values (257, 'GIS Technical Architect', 257);
insert into Poste (idPoste, label, idDepartement) values (258, 'Business Systems Development Analyst', 258);
insert into Poste (idPoste, label, idDepartement) values (259, 'Cost Accountant', 259);
insert into Poste (idPoste, label, idDepartement) values (260, 'Professor', 260);
insert into Poste (idPoste, label, idDepartement) values (261, 'Senior Financial Analyst', 261);
insert into Poste (idPoste, label, idDepartement) values (262, 'Web Developer II', 262);
insert into Poste (idPoste, label, idDepartement) values (263, 'Tax Accountant', 263);
insert into Poste (idPoste, label, idDepartement) values (264, 'Financial Analyst', 264);
insert into Poste (idPoste, label, idDepartement) values (265, 'Chemical Engineer', 265);
insert into Poste (idPoste, label, idDepartement) values (266, 'Food Chemist', 266);
insert into Poste (idPoste, label, idDepartement) values (267, 'Teacher', 267);
insert into Poste (idPoste, label, idDepartement) values (268, 'Cost Accountant', 268);
insert into Poste (idPoste, label, idDepartement) values (269, 'Senior Quality Engineer', 269);
insert into Poste (idPoste, label, idDepartement) values (270, 'VP Sales', 270);
insert into Poste (idPoste, label, idDepartement) values (271, 'General Manager', 271);
insert into Poste (idPoste, label, idDepartement) values (272, 'Paralegal', 272);
insert into Poste (idPoste, label, idDepartement) values (273, 'Research Nurse', 273);
insert into Poste (idPoste, label, idDepartement) values (274, 'Recruiting Manager', 274);
insert into Poste (idPoste, label, idDepartement) values (275, 'Statistician IV', 275);
insert into Poste (idPoste, label, idDepartement) values (276, 'Legal Assistant', 276);
insert into Poste (idPoste, label, idDepartement) values (277, 'Director of Sales', 277);
insert into Poste (idPoste, label, idDepartement) values (278, 'Web Designer II', 278);
insert into Poste (idPoste, label, idDepartement) values (279, 'Environmental Tech', 279);
insert into Poste (idPoste, label, idDepartement) values (280, 'Senior Developer', 280);
insert into Poste (idPoste, label, idDepartement) values (281, 'Programmer Analyst II', 281);
insert into Poste (idPoste, label, idDepartement) values (282, 'Nurse Practicioner', 282);
insert into Poste (idPoste, label, idDepartement) values (283, 'Programmer Analyst II', 283);
insert into Poste (idPoste, label, idDepartement) values (284, 'Accountant III', 284);
insert into Poste (idPoste, label, idDepartement) values (285, 'Project Manager', 285);
insert into Poste (idPoste, label, idDepartement) values (286, 'Food Chemist', 286);
insert into Poste (idPoste, label, idDepartement) values (287, 'Chemical Engineer', 287);
insert into Poste (idPoste, label, idDepartement) values (288, 'Analyst Programmer', 288);
insert into Poste (idPoste, label, idDepartement) values (289, 'General Manager', 289);
insert into Poste (idPoste, label, idDepartement) values (290, 'Registered Nurse', 290);
insert into Poste (idPoste, label, idDepartement) values (291, 'Project Manager', 291);
insert into Poste (idPoste, label, idDepartement) values (292, 'Quality Control Specialist', 292);
insert into Poste (idPoste, label, idDepartement) values (293, 'Health Coach IV', 293);
insert into Poste (idPoste, label, idDepartement) values (294, 'General Manager', 294);
insert into Poste (idPoste, label, idDepartement) values (295, 'Research Assistant IV', 295);
insert into Poste (idPoste, label, idDepartement) values (296, 'Dental Hygienist', 296);
insert into Poste (idPoste, label, idDepartement) values (297, 'Geological Engineer', 297);
insert into Poste (idPoste, label, idDepartement) values (298, 'Media Manager III', 298);
insert into Poste (idPoste, label, idDepartement) values (299, 'Operator', 299);
insert into Poste (idPoste, label, idDepartement) values (300, 'Teacher', 300);
insert into Poste (idPoste, label, idDepartement) values (301, 'Sales Associate', 301);
insert into Poste (idPoste, label, idDepartement) values (302, 'Recruiter', 302);
insert into Poste (idPoste, label, idDepartement) values (303, 'Librarian', 303);
insert into Poste (idPoste, label, idDepartement) values (304, 'Developer I', 304);
insert into Poste (idPoste, label, idDepartement) values (305, 'Developer IV', 305);
insert into Poste (idPoste, label, idDepartement) values (306, 'Staff Accountant I', 306);
insert into Poste (idPoste, label, idDepartement) values (307, 'VP Product Management', 307);
insert into Poste (idPoste, label, idDepartement) values (308, 'Design Engineer', 308);
insert into Poste (idPoste, label, idDepartement) values (309, 'Staff Scientist', 309);
insert into Poste (idPoste, label, idDepartement) values (310, 'Internal Auditor', 310);
insert into Poste (idPoste, label, idDepartement) values (311, 'Nurse Practicioner', 311);
insert into Poste (idPoste, label, idDepartement) values (312, 'Dental Hygienist', 312);
insert into Poste (idPoste, label, idDepartement) values (313, 'VP Accounting', 313);
insert into Poste (idPoste, label, idDepartement) values (314, 'Human Resources Assistant III', 314);
insert into Poste (idPoste, label, idDepartement) values (315, 'Engineer I', 315);
insert into Poste (idPoste, label, idDepartement) values (316, 'Statistician III', 316);
insert into Poste (idPoste, label, idDepartement) values (317, 'Dental Hygienist', 317);
insert into Poste (idPoste, label, idDepartement) values (318, 'Information Systems Manager', 318);
insert into Poste (idPoste, label, idDepartement) values (319, 'Analog Circuit Design manager', 319);
insert into Poste (idPoste, label, idDepartement) values (320, 'Quality Engineer', 320);
insert into Poste (idPoste, label, idDepartement) values (321, 'Account Executive', 321);
insert into Poste (idPoste, label, idDepartement) values (322, 'VP Sales', 322);
insert into Poste (idPoste, label, idDepartement) values (323, 'Office Assistant I', 323);
insert into Poste (idPoste, label, idDepartement) values (324, 'Electrical Engineer', 324);
insert into Poste (idPoste, label, idDepartement) values (325, 'Accountant II', 325);
insert into Poste (idPoste, label, idDepartement) values (326, 'Actuary', 326);
insert into Poste (idPoste, label, idDepartement) values (327, 'Senior Cost Accountant', 327);
insert into Poste (idPoste, label, idDepartement) values (328, 'Automation Specialist IV', 328);
insert into Poste (idPoste, label, idDepartement) values (329, 'Account Coordinator', 329);
insert into Poste (idPoste, label, idDepartement) values (330, 'Design Engineer', 330);
insert into Poste (idPoste, label, idDepartement) values (331, 'Office Assistant I', 331);
insert into Poste (idPoste, label, idDepartement) values (332, 'Director of Sales', 332);
insert into Poste (idPoste, label, idDepartement) values (333, 'Analog Circuit Design manager', 333);
insert into Poste (idPoste, label, idDepartement) values (334, 'Account Executive', 334);
insert into Poste (idPoste, label, idDepartement) values (335, 'Accounting Assistant III', 335);
insert into Poste (idPoste, label, idDepartement) values (336, 'Accountant III', 336);
insert into Poste (idPoste, label, idDepartement) values (337, 'Structural Analysis Engineer', 337);
insert into Poste (idPoste, label, idDepartement) values (338, 'Assistant Media Planner', 338);
insert into Poste (idPoste, label, idDepartement) values (339, 'Administrative Assistant III', 339);
insert into Poste (idPoste, label, idDepartement) values (340, 'General Manager', 340);
insert into Poste (idPoste, label, idDepartement) values (341, 'Biostatistician II', 341);
insert into Poste (idPoste, label, idDepartement) values (342, 'Systems Administrator IV', 342);
insert into Poste (idPoste, label, idDepartement) values (343, 'Structural Engineer', 343);
insert into Poste (idPoste, label, idDepartement) values (344, 'Nurse Practicioner', 344);
insert into Poste (idPoste, label, idDepartement) values (345, 'Programmer Analyst I', 345);
insert into Poste (idPoste, label, idDepartement) values (346, 'Quality Control Specialist', 346);
insert into Poste (idPoste, label, idDepartement) values (347, 'Account Executive', 347);
insert into Poste (idPoste, label, idDepartement) values (348, 'Staff Accountant I', 348);
insert into Poste (idPoste, label, idDepartement) values (349, 'Recruiting Manager', 349);
insert into Poste (idPoste, label, idDepartement) values (350, 'General Manager', 350);
insert into Poste (idPoste, label, idDepartement) values (351, 'Clinical Specialist', 351);
insert into Poste (idPoste, label, idDepartement) values (352, 'Speech Pathologist', 352);
insert into Poste (idPoste, label, idDepartement) values (353, 'Actuary', 353);
insert into Poste (idPoste, label, idDepartement) values (354, 'Biostatistician III', 354);
insert into Poste (idPoste, label, idDepartement) values (355, 'Associate Professor', 355);
insert into Poste (idPoste, label, idDepartement) values (356, 'Account Representative III', 356);
insert into Poste (idPoste, label, idDepartement) values (357, 'Financial Analyst', 357);
insert into Poste (idPoste, label, idDepartement) values (358, 'Analyst Programmer', 358);
insert into Poste (idPoste, label, idDepartement) values (359, 'Help Desk Operator', 359);
insert into Poste (idPoste, label, idDepartement) values (360, 'Senior Editor', 360);
insert into Poste (idPoste, label, idDepartement) values (361, 'Help Desk Operator', 361);
insert into Poste (idPoste, label, idDepartement) values (362, 'Senior Quality Engineer', 362);
insert into Poste (idPoste, label, idDepartement) values (363, 'Graphic Designer', 363);
insert into Poste (idPoste, label, idDepartement) values (364, 'Staff Scientist', 364);
insert into Poste (idPoste, label, idDepartement) values (365, 'Assistant Professor', 365);
insert into Poste (idPoste, label, idDepartement) values (366, 'Assistant Media Planner', 366);
insert into Poste (idPoste, label, idDepartement) values (367, 'Clinical Specialist', 367);
insert into Poste (idPoste, label, idDepartement) values (368, 'Electrical Engineer', 368);
insert into Poste (idPoste, label, idDepartement) values (369, 'Pharmacist', 369);
insert into Poste (idPoste, label, idDepartement) values (370, 'Research Assistant II', 370);
insert into Poste (idPoste, label, idDepartement) values (371, 'Media Manager III', 371);
insert into Poste (idPoste, label, idDepartement) values (372, 'Software Engineer I', 372);
insert into Poste (idPoste, label, idDepartement) values (373, 'Data Coordiator', 373);
insert into Poste (idPoste, label, idDepartement) values (374, 'Data Coordiator', 374);
insert into Poste (idPoste, label, idDepartement) values (375, 'Physical Therapy Assistant', 375);
insert into Poste (idPoste, label, idDepartement) values (376, 'Paralegal', 376);
insert into Poste (idPoste, label, idDepartement) values (377, 'Business Systems Development Analyst', 377);
insert into Poste (idPoste, label, idDepartement) values (378, 'Systems Administrator III', 378);
insert into Poste (idPoste, label, idDepartement) values (379, 'Analyst Programmer', 379);
insert into Poste (idPoste, label, idDepartement) values (380, 'Recruiter', 380);
insert into Poste (idPoste, label, idDepartement) values (381, 'Programmer Analyst III', 381);
insert into Poste (idPoste, label, idDepartement) values (382, 'Accounting Assistant II', 382);
insert into Poste (idPoste, label, idDepartement) values (383, 'Senior Developer', 383);
insert into Poste (idPoste, label, idDepartement) values (384, 'Cost Accountant', 384);
insert into Poste (idPoste, label, idDepartement) values (385, 'Occupational Therapist', 385);
insert into Poste (idPoste, label, idDepartement) values (386, 'Environmental Specialist', 386);
insert into Poste (idPoste, label, idDepartement) values (387, 'Senior Editor', 387);
insert into Poste (idPoste, label, idDepartement) values (388, 'Systems Administrator I', 388);
insert into Poste (idPoste, label, idDepartement) values (389, 'GIS Technical Architect', 389);
insert into Poste (idPoste, label, idDepartement) values (390, 'Administrative Assistant I', 390);
insert into Poste (idPoste, label, idDepartement) values (391, 'Statistician III', 391);
insert into Poste (idPoste, label, idDepartement) values (392, 'Desktop Support Technician', 392);
insert into Poste (idPoste, label, idDepartement) values (393, 'Project Manager', 393);
insert into Poste (idPoste, label, idDepartement) values (394, 'Automation Specialist III', 394);
insert into Poste (idPoste, label, idDepartement) values (395, 'Research Nurse', 395);
insert into Poste (idPoste, label, idDepartement) values (396, 'Budget/Accounting Analyst II', 396);
insert into Poste (idPoste, label, idDepartement) values (397, 'Occupational Therapist', 397);
insert into Poste (idPoste, label, idDepartement) values (398, 'Assistant Professor', 398);
insert into Poste (idPoste, label, idDepartement) values (399, 'Quality Control Specialist', 399);
insert into Poste (idPoste, label, idDepartement) values (400, 'Food Chemist', 400);
insert into Poste (idPoste, label, idDepartement) values (401, 'Librarian', 401);
insert into Poste (idPoste, label, idDepartement) values (402, 'Project Manager', 402);
insert into Poste (idPoste, label, idDepartement) values (403, 'Geological Engineer', 403);
insert into Poste (idPoste, label, idDepartement) values (404, 'Financial Advisor', 404);
insert into Poste (idPoste, label, idDepartement) values (405, 'Web Designer IV', 405);
insert into Poste (idPoste, label, idDepartement) values (406, 'Recruiting Manager', 406);
insert into Poste (idPoste, label, idDepartement) values (407, 'Account Coordinator', 407);
insert into Poste (idPoste, label, idDepartement) values (408, 'Financial Advisor', 408);
insert into Poste (idPoste, label, idDepartement) values (409, 'Senior Developer', 409);
insert into Poste (idPoste, label, idDepartement) values (410, 'Data Coordiator', 410);
insert into Poste (idPoste, label, idDepartement) values (411, 'Marketing Manager', 411);
insert into Poste (idPoste, label, idDepartement) values (412, 'Data Coordiator', 412);
insert into Poste (idPoste, label, idDepartement) values (413, 'Media Manager I', 413);
insert into Poste (idPoste, label, idDepartement) values (414, 'Analog Circuit Design manager', 414);
insert into Poste (idPoste, label, idDepartement) values (415, 'Automation Specialist II', 415);
insert into Poste (idPoste, label, idDepartement) values (416, 'Director of Sales', 416);
insert into Poste (idPoste, label, idDepartement) values (417, 'Systems Administrator I', 417);
insert into Poste (idPoste, label, idDepartement) values (418, 'VP Sales', 418);
insert into Poste (idPoste, label, idDepartement) values (419, 'Biostatistician IV', 419);
insert into Poste (idPoste, label, idDepartement) values (420, 'Cost Accountant', 420);
insert into Poste (idPoste, label, idDepartement) values (421, 'Dental Hygienist', 421);
insert into Poste (idPoste, label, idDepartement) values (422, 'Senior Financial Analyst', 422);
insert into Poste (idPoste, label, idDepartement) values (423, 'Structural Engineer', 423);
insert into Poste (idPoste, label, idDepartement) values (424, 'Computer Systems Analyst IV', 424);
insert into Poste (idPoste, label, idDepartement) values (425, 'Automation Specialist IV', 425);
insert into Poste (idPoste, label, idDepartement) values (426, 'Assistant Media Planner', 426);
insert into Poste (idPoste, label, idDepartement) values (427, 'Structural Analysis Engineer', 427);
insert into Poste (idPoste, label, idDepartement) values (428, 'Help Desk Operator', 428);
insert into Poste (idPoste, label, idDepartement) values (429, 'Structural Analysis Engineer', 429);
insert into Poste (idPoste, label, idDepartement) values (430, 'Research Nurse', 430);
insert into Poste (idPoste, label, idDepartement) values (431, 'Environmental Specialist', 431);
insert into Poste (idPoste, label, idDepartement) values (432, 'Senior Developer', 432);
insert into Poste (idPoste, label, idDepartement) values (433, 'Safety Technician II', 433);
insert into Poste (idPoste, label, idDepartement) values (434, 'Environmental Specialist', 434);
insert into Poste (idPoste, label, idDepartement) values (435, 'Operator', 435);
insert into Poste (idPoste, label, idDepartement) values (436, 'VP Sales', 436);
insert into Poste (idPoste, label, idDepartement) values (437, 'Senior Financial Analyst', 437);
insert into Poste (idPoste, label, idDepartement) values (438, 'Actuary', 438);
insert into Poste (idPoste, label, idDepartement) values (439, 'Recruiter', 439);
insert into Poste (idPoste, label, idDepartement) values (440, 'Food Chemist', 440);
insert into Poste (idPoste, label, idDepartement) values (441, 'Geologist III', 441);
insert into Poste (idPoste, label, idDepartement) values (442, 'Research Assistant I', 442);
insert into Poste (idPoste, label, idDepartement) values (443, 'Recruiter', 443);
insert into Poste (idPoste, label, idDepartement) values (444, 'Geological Engineer', 444);
insert into Poste (idPoste, label, idDepartement) values (445, 'Social Worker', 445);
insert into Poste (idPoste, label, idDepartement) values (446, 'Senior Financial Analyst', 446);
insert into Poste (idPoste, label, idDepartement) values (447, 'General Manager', 447);
insert into Poste (idPoste, label, idDepartement) values (448, 'Compensation Analyst', 448);
insert into Poste (idPoste, label, idDepartement) values (449, 'Programmer Analyst IV', 449);
insert into Poste (idPoste, label, idDepartement) values (450, 'Teacher', 450);
insert into Poste (idPoste, label, idDepartement) values (451, 'Research Nurse', 451);
insert into Poste (idPoste, label, idDepartement) values (452, 'Software Consultant', 452);
insert into Poste (idPoste, label, idDepartement) values (453, 'Research Assistant IV', 453);
insert into Poste (idPoste, label, idDepartement) values (454, 'Community Outreach Specialist', 454);
insert into Poste (idPoste, label, idDepartement) values (455, 'Physical Therapy Assistant', 455);
insert into Poste (idPoste, label, idDepartement) values (456, 'Administrative Officer', 456);
insert into Poste (idPoste, label, idDepartement) values (457, 'Registered Nurse', 457);
insert into Poste (idPoste, label, idDepartement) values (458, 'Nurse', 458);
insert into Poste (idPoste, label, idDepartement) values (459, 'Staff Scientist', 459);
insert into Poste (idPoste, label, idDepartement) values (460, 'Account Coordinator', 460);
insert into Poste (idPoste, label, idDepartement) values (461, 'Design Engineer', 461);
insert into Poste (idPoste, label, idDepartement) values (462, 'Professor', 462);
insert into Poste (idPoste, label, idDepartement) values (463, 'Geologist IV', 463);
insert into Poste (idPoste, label, idDepartement) values (464, 'Technical Writer', 464);
insert into Poste (idPoste, label, idDepartement) values (465, 'Social Worker', 465);
insert into Poste (idPoste, label, idDepartement) values (466, 'Design Engineer', 466);
insert into Poste (idPoste, label, idDepartement) values (467, 'Software Engineer IV', 467);
insert into Poste (idPoste, label, idDepartement) values (468, 'Technical Writer', 468);
insert into Poste (idPoste, label, idDepartement) values (469, 'VP Product Management', 469);
insert into Poste (idPoste, label, idDepartement) values (470, 'Financial Advisor', 470);
insert into Poste (idPoste, label, idDepartement) values (471, 'Quality Control Specialist', 471);
insert into Poste (idPoste, label, idDepartement) values (472, 'Nuclear Power Engineer', 472);
insert into Poste (idPoste, label, idDepartement) values (473, 'Structural Analysis Engineer', 473);
insert into Poste (idPoste, label, idDepartement) values (474, 'Sales Representative', 474);
insert into Poste (idPoste, label, idDepartement) values (475, 'Senior Editor', 475);
insert into Poste (idPoste, label, idDepartement) values (476, 'Data Coordiator', 476);
insert into Poste (idPoste, label, idDepartement) values (477, 'Occupational Therapist', 477);
insert into Poste (idPoste, label, idDepartement) values (478, 'Senior Developer', 478);
insert into Poste (idPoste, label, idDepartement) values (479, 'Junior Executive', 479);
insert into Poste (idPoste, label, idDepartement) values (480, 'Chemical Engineer', 480);
insert into Poste (idPoste, label, idDepartement) values (481, 'Engineer II', 481);
insert into Poste (idPoste, label, idDepartement) values (482, 'Database Administrator III', 482);
insert into Poste (idPoste, label, idDepartement) values (483, 'Biostatistician IV', 483);
insert into Poste (idPoste, label, idDepartement) values (484, 'Human Resources Manager', 484);
insert into Poste (idPoste, label, idDepartement) values (485, 'Chief Design Engineer', 485);
insert into Poste (idPoste, label, idDepartement) values (486, 'Dental Hygienist', 486);
insert into Poste (idPoste, label, idDepartement) values (487, 'Account Executive', 487);
insert into Poste (idPoste, label, idDepartement) values (488, 'VP Product Management', 488);
insert into Poste (idPoste, label, idDepartement) values (489, 'Research Associate', 489);
insert into Poste (idPoste, label, idDepartement) values (490, 'Payment Adjustment Coordinator', 490);
insert into Poste (idPoste, label, idDepartement) values (491, 'Internal Auditor', 491);
insert into Poste (idPoste, label, idDepartement) values (492, 'Automation Specialist IV', 492);
insert into Poste (idPoste, label, idDepartement) values (493, 'VP Sales', 493);
insert into Poste (idPoste, label, idDepartement) values (494, 'Operator', 494);
insert into Poste (idPoste, label, idDepartement) values (495, 'Senior Quality Engineer', 495);
insert into Poste (idPoste, label, idDepartement) values (496, 'Editor', 496);
insert into Poste (idPoste, label, idDepartement) values (497, 'Electrical Engineer', 497);
insert into Poste (idPoste, label, idDepartement) values (498, 'Research Associate', 498);
insert into Poste (idPoste, label, idDepartement) values (499, 'Pharmacist', 499);
insert into Poste (idPoste, label, idDepartement) values (500, 'Help Desk Technician', 500);
insert into Poste (idPoste, label, idDepartement) values (501, 'Junior Executive', 501);
insert into Poste (idPoste, label, idDepartement) values (502, 'Food Chemist', 502);
insert into Poste (idPoste, label, idDepartement) values (503, 'Assistant Manager', 503);
insert into Poste (idPoste, label, idDepartement) values (504, 'Analyst Programmer', 504);
insert into Poste (idPoste, label, idDepartement) values (505, 'Senior Developer', 505);
insert into Poste (idPoste, label, idDepartement) values (506, 'Human Resources Manager', 506);
insert into Poste (idPoste, label, idDepartement) values (507, 'Chemical Engineer', 507);
insert into Poste (idPoste, label, idDepartement) values (508, 'Payment Adjustment Coordinator', 508);
insert into Poste (idPoste, label, idDepartement) values (509, 'Chemical Engineer', 509);
insert into Poste (idPoste, label, idDepartement) values (510, 'Registered Nurse', 510);
insert into Poste (idPoste, label, idDepartement) values (511, 'Payment Adjustment Coordinator', 511);
insert into Poste (idPoste, label, idDepartement) values (512, 'Dental Hygienist', 512);
insert into Poste (idPoste, label, idDepartement) values (513, 'Research Nurse', 513);
insert into Poste (idPoste, label, idDepartement) values (514, 'Staff Scientist', 514);
insert into Poste (idPoste, label, idDepartement) values (515, 'Research Nurse', 515);
insert into Poste (idPoste, label, idDepartement) values (516, 'Recruiting Manager', 516);
insert into Poste (idPoste, label, idDepartement) values (517, 'Environmental Specialist', 517);
insert into Poste (idPoste, label, idDepartement) values (518, 'Help Desk Technician', 518);
insert into Poste (idPoste, label, idDepartement) values (519, 'Editor', 519);
insert into Poste (idPoste, label, idDepartement) values (520, 'Data Coordiator', 520);
insert into Poste (idPoste, label, idDepartement) values (521, 'Payment Adjustment Coordinator', 521);
insert into Poste (idPoste, label, idDepartement) values (522, 'VP Accounting', 522);
insert into Poste (idPoste, label, idDepartement) values (523, 'Nuclear Power Engineer', 523);
insert into Poste (idPoste, label, idDepartement) values (524, 'Paralegal', 524);
insert into Poste (idPoste, label, idDepartement) values (525, 'Senior Editor', 525);
insert into Poste (idPoste, label, idDepartement) values (526, 'Professor', 526);
insert into Poste (idPoste, label, idDepartement) values (527, 'Occupational Therapist', 527);
insert into Poste (idPoste, label, idDepartement) values (528, 'Business Systems Development Analyst', 528);
insert into Poste (idPoste, label, idDepartement) values (529, 'Software Test Engineer IV', 529);
insert into Poste (idPoste, label, idDepartement) values (530, 'Assistant Professor', 530);
insert into Poste (idPoste, label, idDepartement) values (531, 'Account Executive', 531);
insert into Poste (idPoste, label, idDepartement) values (532, 'Operator', 532);
insert into Poste (idPoste, label, idDepartement) values (533, 'Director of Sales', 533);
insert into Poste (idPoste, label, idDepartement) values (534, 'Professor', 534);
insert into Poste (idPoste, label, idDepartement) values (535, 'Web Developer I', 535);
insert into Poste (idPoste, label, idDepartement) values (536, 'Internal Auditor', 536);
insert into Poste (idPoste, label, idDepartement) values (537, 'Help Desk Operator', 537);
insert into Poste (idPoste, label, idDepartement) values (538, 'Computer Systems Analyst I', 538);
insert into Poste (idPoste, label, idDepartement) values (539, 'Administrative Officer', 539);
insert into Poste (idPoste, label, idDepartement) values (540, 'Computer Systems Analyst II', 540);
insert into Poste (idPoste, label, idDepartement) values (541, 'Sales Representative', 541);
insert into Poste (idPoste, label, idDepartement) values (542, 'Senior Quality Engineer', 542);
insert into Poste (idPoste, label, idDepartement) values (543, 'Assistant Professor', 543);
insert into Poste (idPoste, label, idDepartement) values (544, 'Software Consultant', 544);
insert into Poste (idPoste, label, idDepartement) values (545, 'Internal Auditor', 545);
insert into Poste (idPoste, label, idDepartement) values (546, 'Business Systems Development Analyst', 546);
insert into Poste (idPoste, label, idDepartement) values (547, 'Quality Control Specialist', 547);
insert into Poste (idPoste, label, idDepartement) values (548, 'Mechanical Systems Engineer', 548);
insert into Poste (idPoste, label, idDepartement) values (549, 'Payment Adjustment Coordinator', 549);
insert into Poste (idPoste, label, idDepartement) values (550, 'Office Assistant I', 550);
insert into Poste (idPoste, label, idDepartement) values (551, 'Paralegal', 551);
insert into Poste (idPoste, label, idDepartement) values (552, 'Food Chemist', 552);
insert into Poste (idPoste, label, idDepartement) values (553, 'Legal Assistant', 553);
insert into Poste (idPoste, label, idDepartement) values (554, 'Design Engineer', 554);
insert into Poste (idPoste, label, idDepartement) values (555, 'Software Engineer IV', 555);
insert into Poste (idPoste, label, idDepartement) values (556, 'Geological Engineer', 556);
insert into Poste (idPoste, label, idDepartement) values (557, 'Web Designer II', 557);
insert into Poste (idPoste, label, idDepartement) values (558, 'Teacher', 558);
insert into Poste (idPoste, label, idDepartement) values (559, 'Pharmacist', 559);
insert into Poste (idPoste, label, idDepartement) values (560, 'Biostatistician II', 560);
insert into Poste (idPoste, label, idDepartement) values (561, 'General Manager', 561);
insert into Poste (idPoste, label, idDepartement) values (562, 'Senior Quality Engineer', 562);
insert into Poste (idPoste, label, idDepartement) values (563, 'Mechanical Systems Engineer', 563);
insert into Poste (idPoste, label, idDepartement) values (564, 'Desktop Support Technician', 564);
insert into Poste (idPoste, label, idDepartement) values (565, 'Computer Systems Analyst IV', 565);
insert into Poste (idPoste, label, idDepartement) values (566, 'Teacher', 566);
insert into Poste (idPoste, label, idDepartement) values (567, 'VP Product Management', 567);
insert into Poste (idPoste, label, idDepartement) values (568, 'Programmer Analyst II', 568);
insert into Poste (idPoste, label, idDepartement) values (569, 'Biostatistician II', 569);
insert into Poste (idPoste, label, idDepartement) values (570, 'Staff Scientist', 570);
insert into Poste (idPoste, label, idDepartement) values (571, 'Teacher', 571);
insert into Poste (idPoste, label, idDepartement) values (572, 'Office Assistant IV', 572);
insert into Poste (idPoste, label, idDepartement) values (573, 'Computer Systems Analyst III', 573);
insert into Poste (idPoste, label, idDepartement) values (574, 'Programmer IV', 574);
insert into Poste (idPoste, label, idDepartement) values (575, 'Data Coordiator', 575);
insert into Poste (idPoste, label, idDepartement) values (576, 'VP Quality Control', 576);
insert into Poste (idPoste, label, idDepartement) values (577, 'Registered Nurse', 577);
insert into Poste (idPoste, label, idDepartement) values (578, 'Programmer IV', 578);
insert into Poste (idPoste, label, idDepartement) values (579, 'Quality Engineer', 579);
insert into Poste (idPoste, label, idDepartement) values (580, 'Graphic Designer', 580);
insert into Poste (idPoste, label, idDepartement) values (581, 'Quality Control Specialist', 581);
insert into Poste (idPoste, label, idDepartement) values (582, 'Accountant II', 582);
insert into Poste (idPoste, label, idDepartement) values (583, 'Cost Accountant', 583);
insert into Poste (idPoste, label, idDepartement) values (584, 'Office Assistant IV', 584);
insert into Poste (idPoste, label, idDepartement) values (585, 'Administrative Officer', 585);
insert into Poste (idPoste, label, idDepartement) values (586, 'Desktop Support Technician', 586);
insert into Poste (idPoste, label, idDepartement) values (587, 'Staff Accountant IV', 587);
insert into Poste (idPoste, label, idDepartement) values (588, 'VP Marketing', 588);
insert into Poste (idPoste, label, idDepartement) values (589, 'Financial Analyst', 589);
insert into Poste (idPoste, label, idDepartement) values (590, 'Physical Therapy Assistant', 590);
insert into Poste (idPoste, label, idDepartement) values (591, 'Statistician I', 591);
insert into Poste (idPoste, label, idDepartement) values (592, 'Director of Sales', 592);
insert into Poste (idPoste, label, idDepartement) values (593, 'Legal Assistant', 593);
insert into Poste (idPoste, label, idDepartement) values (594, 'Chemical Engineer', 594);
insert into Poste (idPoste, label, idDepartement) values (595, 'Graphic Designer', 595);
insert into Poste (idPoste, label, idDepartement) values (596, 'VP Product Management', 596);
insert into Poste (idPoste, label, idDepartement) values (597, 'Marketing Assistant', 597);
insert into Poste (idPoste, label, idDepartement) values (598, 'Accounting Assistant IV', 598);
insert into Poste (idPoste, label, idDepartement) values (599, 'Staff Accountant II', 599);
insert into Poste (idPoste, label, idDepartement) values (600, 'Pharmacist', 600);
insert into Poste (idPoste, label, idDepartement) values (601, 'Systems Administrator II', 601);
insert into Poste (idPoste, label, idDepartement) values (602, 'Internal Auditor', 602);
insert into Poste (idPoste, label, idDepartement) values (603, 'Help Desk Operator', 603);
insert into Poste (idPoste, label, idDepartement) values (604, 'Community Outreach Specialist', 604);
insert into Poste (idPoste, label, idDepartement) values (605, 'Developer III', 605);
insert into Poste (idPoste, label, idDepartement) values (606, 'Nurse', 606);
insert into Poste (idPoste, label, idDepartement) values (607, 'Programmer II', 607);
insert into Poste (idPoste, label, idDepartement) values (608, 'VP Product Management', 608);
insert into Poste (idPoste, label, idDepartement) values (609, 'Research Associate', 609);
insert into Poste (idPoste, label, idDepartement) values (610, 'Executive Secretary', 610);
insert into Poste (idPoste, label, idDepartement) values (611, 'Electrical Engineer', 611);
insert into Poste (idPoste, label, idDepartement) values (612, 'Database Administrator I', 612);
insert into Poste (idPoste, label, idDepartement) values (613, 'Environmental Tech', 613);
insert into Poste (idPoste, label, idDepartement) values (614, 'Design Engineer', 614);
insert into Poste (idPoste, label, idDepartement) values (615, 'Analog Circuit Design manager', 615);
insert into Poste (idPoste, label, idDepartement) values (616, 'Accountant III', 616);
insert into Poste (idPoste, label, idDepartement) values (617, 'Junior Executive', 617);
insert into Poste (idPoste, label, idDepartement) values (618, 'Speech Pathologist', 618);
insert into Poste (idPoste, label, idDepartement) values (619, 'Accounting Assistant III', 619);
insert into Poste (idPoste, label, idDepartement) values (620, 'Human Resources Manager', 620);
insert into Poste (idPoste, label, idDepartement) values (621, 'GIS Technical Architect', 621);
insert into Poste (idPoste, label, idDepartement) values (622, 'Account Coordinator', 622);
insert into Poste (idPoste, label, idDepartement) values (623, 'Account Coordinator', 623);
insert into Poste (idPoste, label, idDepartement) values (624, 'VP Sales', 624);
insert into Poste (idPoste, label, idDepartement) values (625, 'Account Coordinator', 625);
insert into Poste (idPoste, label, idDepartement) values (626, 'Marketing Manager', 626);
insert into Poste (idPoste, label, idDepartement) values (627, 'Pharmacist', 627);
insert into Poste (idPoste, label, idDepartement) values (628, 'Senior Cost Accountant', 628);
insert into Poste (idPoste, label, idDepartement) values (629, 'Web Developer III', 629);
insert into Poste (idPoste, label, idDepartement) values (630, 'Senior Developer', 630);
insert into Poste (idPoste, label, idDepartement) values (631, 'Structural Analysis Engineer', 631);
insert into Poste (idPoste, label, idDepartement) values (632, 'Operator', 632);
insert into Poste (idPoste, label, idDepartement) values (633, 'Chemical Engineer', 633);
insert into Poste (idPoste, label, idDepartement) values (634, 'Desktop Support Technician', 634);
insert into Poste (idPoste, label, idDepartement) values (635, 'Junior Executive', 635);
insert into Poste (idPoste, label, idDepartement) values (636, 'Civil Engineer', 636);
insert into Poste (idPoste, label, idDepartement) values (637, 'Physical Therapy Assistant', 637);
insert into Poste (idPoste, label, idDepartement) values (638, 'Account Executive', 638);
insert into Poste (idPoste, label, idDepartement) values (639, 'Legal Assistant', 639);
insert into Poste (idPoste, label, idDepartement) values (640, 'Editor', 640);
insert into Poste (idPoste, label, idDepartement) values (641, 'Professor', 641);
insert into Poste (idPoste, label, idDepartement) values (642, 'Electrical Engineer', 642);
insert into Poste (idPoste, label, idDepartement) values (643, 'VP Marketing', 643);
insert into Poste (idPoste, label, idDepartement) values (644, 'Nurse Practicioner', 644);
insert into Poste (idPoste, label, idDepartement) values (645, 'Web Designer IV', 645);
insert into Poste (idPoste, label, idDepartement) values (646, 'Financial Advisor', 646);
insert into Poste (idPoste, label, idDepartement) values (647, 'Professor', 647);
insert into Poste (idPoste, label, idDepartement) values (648, 'Programmer IV', 648);
insert into Poste (idPoste, label, idDepartement) values (649, 'Biostatistician IV', 649);
insert into Poste (idPoste, label, idDepartement) values (650, 'Automation Specialist III', 650);
insert into Poste (idPoste, label, idDepartement) values (651, 'Occupational Therapist', 651);
insert into Poste (idPoste, label, idDepartement) values (652, 'Graphic Designer', 652);
insert into Poste (idPoste, label, idDepartement) values (653, 'Sales Associate', 653);
insert into Poste (idPoste, label, idDepartement) values (654, 'Payment Adjustment Coordinator', 654);
insert into Poste (idPoste, label, idDepartement) values (655, 'Human Resources Assistant III', 655);
insert into Poste (idPoste, label, idDepartement) values (656, 'VP Accounting', 656);
insert into Poste (idPoste, label, idDepartement) values (657, 'Senior Developer', 657);
insert into Poste (idPoste, label, idDepartement) values (658, 'Project Manager', 658);
insert into Poste (idPoste, label, idDepartement) values (659, 'Account Coordinator', 659);
insert into Poste (idPoste, label, idDepartement) values (660, 'Account Executive', 660);
insert into Poste (idPoste, label, idDepartement) values (661, 'Technical Writer', 661);
insert into Poste (idPoste, label, idDepartement) values (662, 'Senior Cost Accountant', 662);
insert into Poste (idPoste, label, idDepartement) values (663, 'Accountant IV', 663);
insert into Poste (idPoste, label, idDepartement) values (664, 'Budget/Accounting Analyst III', 664);
insert into Poste (idPoste, label, idDepartement) values (665, 'Nuclear Power Engineer', 665);
insert into Poste (idPoste, label, idDepartement) values (666, 'Design Engineer', 666);
insert into Poste (idPoste, label, idDepartement) values (667, 'Quality Control Specialist', 667);
insert into Poste (idPoste, label, idDepartement) values (668, 'Occupational Therapist', 668);
insert into Poste (idPoste, label, idDepartement) values (669, 'Paralegal', 669);
insert into Poste (idPoste, label, idDepartement) values (670, 'Sales Representative', 670);
insert into Poste (idPoste, label, idDepartement) values (671, 'Internal Auditor', 671);
insert into Poste (idPoste, label, idDepartement) values (672, 'Environmental Specialist', 672);
insert into Poste (idPoste, label, idDepartement) values (673, 'Help Desk Operator', 673);
insert into Poste (idPoste, label, idDepartement) values (674, 'Assistant Manager', 674);
insert into Poste (idPoste, label, idDepartement) values (675, 'Sales Associate', 675);
insert into Poste (idPoste, label, idDepartement) values (676, 'Safety Technician I', 676);
insert into Poste (idPoste, label, idDepartement) values (677, 'Help Desk Operator', 677);
insert into Poste (idPoste, label, idDepartement) values (678, 'Developer II', 678);
insert into Poste (idPoste, label, idDepartement) values (679, 'Physical Therapy Assistant', 679);
insert into Poste (idPoste, label, idDepartement) values (680, 'Geologist IV', 680);
insert into Poste (idPoste, label, idDepartement) values (681, 'Marketing Assistant', 681);
insert into Poste (idPoste, label, idDepartement) values (682, 'Programmer II', 682);
insert into Poste (idPoste, label, idDepartement) values (683, 'Senior Quality Engineer', 683);
insert into Poste (idPoste, label, idDepartement) values (684, 'Professor', 684);
insert into Poste (idPoste, label, idDepartement) values (685, 'Data Coordiator', 685);
insert into Poste (idPoste, label, idDepartement) values (686, 'Junior Executive', 686);
insert into Poste (idPoste, label, idDepartement) values (687, 'Project Manager', 687);
insert into Poste (idPoste, label, idDepartement) values (688, 'Statistician IV', 688);
insert into Poste (idPoste, label, idDepartement) values (689, 'Paralegal', 689);
insert into Poste (idPoste, label, idDepartement) values (690, 'Statistician IV', 690);
insert into Poste (idPoste, label, idDepartement) values (691, 'Database Administrator III', 691);
insert into Poste (idPoste, label, idDepartement) values (692, 'Financial Analyst', 692);
insert into Poste (idPoste, label, idDepartement) values (693, 'Physical Therapy Assistant', 693);
insert into Poste (idPoste, label, idDepartement) values (694, 'Marketing Assistant', 694);
insert into Poste (idPoste, label, idDepartement) values (695, 'Accounting Assistant III', 695);
insert into Poste (idPoste, label, idDepartement) values (696, 'Biostatistician III', 696);
insert into Poste (idPoste, label, idDepartement) values (697, 'Teacher', 697);
insert into Poste (idPoste, label, idDepartement) values (698, 'Media Manager II', 698);
insert into Poste (idPoste, label, idDepartement) values (699, 'Administrative Assistant I', 699);
insert into Poste (idPoste, label, idDepartement) values (700, 'Internal Auditor', 700);
insert into Poste (idPoste, label, idDepartement) values (701, 'Editor', 701);
insert into Poste (idPoste, label, idDepartement) values (702, 'VP Accounting', 702);
insert into Poste (idPoste, label, idDepartement) values (703, 'Senior Financial Analyst', 703);
insert into Poste (idPoste, label, idDepartement) values (704, 'Paralegal', 704);
insert into Poste (idPoste, label, idDepartement) values (705, 'Administrative Assistant III', 705);
insert into Poste (idPoste, label, idDepartement) values (706, 'Dental Hygienist', 706);
insert into Poste (idPoste, label, idDepartement) values (707, 'Actuary', 707);
insert into Poste (idPoste, label, idDepartement) values (708, 'Research Assistant I', 708);
insert into Poste (idPoste, label, idDepartement) values (709, 'Mechanical Systems Engineer', 709);
insert into Poste (idPoste, label, idDepartement) values (710, 'Payment Adjustment Coordinator', 710);
insert into Poste (idPoste, label, idDepartement) values (711, 'Environmental Tech', 711);
insert into Poste (idPoste, label, idDepartement) values (712, 'Assistant Media Planner', 712);
insert into Poste (idPoste, label, idDepartement) values (713, 'Account Executive', 713);
insert into Poste (idPoste, label, idDepartement) values (714, 'Executive Secretary', 714);
insert into Poste (idPoste, label, idDepartement) values (715, 'Analyst Programmer', 715);
insert into Poste (idPoste, label, idDepartement) values (716, 'Staff Accountant IV', 716);
insert into Poste (idPoste, label, idDepartement) values (717, 'Human Resources Assistant III', 717);
insert into Poste (idPoste, label, idDepartement) values (718, 'Physical Therapy Assistant', 718);
insert into Poste (idPoste, label, idDepartement) values (719, 'Human Resources Assistant IV', 719);
insert into Poste (idPoste, label, idDepartement) values (720, 'Occupational Therapist', 720);
insert into Poste (idPoste, label, idDepartement) values (721, 'Developer IV', 721);
insert into Poste (idPoste, label, idDepartement) values (722, 'Health Coach IV', 722);
insert into Poste (idPoste, label, idDepartement) values (723, 'VP Quality Control', 723);
insert into Poste (idPoste, label, idDepartement) values (724, 'Payment Adjustment Coordinator', 724);
insert into Poste (idPoste, label, idDepartement) values (725, 'Junior Executive', 725);
insert into Poste (idPoste, label, idDepartement) values (726, 'Programmer Analyst IV', 726);
insert into Poste (idPoste, label, idDepartement) values (727, 'Developer II', 727);
insert into Poste (idPoste, label, idDepartement) values (728, 'Assistant Media Planner', 728);
insert into Poste (idPoste, label, idDepartement) values (729, 'Payment Adjustment Coordinator', 729);
insert into Poste (idPoste, label, idDepartement) values (730, 'Safety Technician IV', 730);
insert into Poste (idPoste, label, idDepartement) values (731, 'Assistant Media Planner', 731);
insert into Poste (idPoste, label, idDepartement) values (732, 'Senior Cost Accountant', 732);
insert into Poste (idPoste, label, idDepartement) values (733, 'Chief Design Engineer', 733);
insert into Poste (idPoste, label, idDepartement) values (734, 'Executive Secretary', 734);
insert into Poste (idPoste, label, idDepartement) values (735, 'Pharmacist', 735);
insert into Poste (idPoste, label, idDepartement) values (736, 'Developer I', 736);
insert into Poste (idPoste, label, idDepartement) values (737, 'Quality Engineer', 737);
insert into Poste (idPoste, label, idDepartement) values (738, 'Professor', 738);
insert into Poste (idPoste, label, idDepartement) values (739, 'VP Sales', 739);
insert into Poste (idPoste, label, idDepartement) values (740, 'Biostatistician III', 740);
insert into Poste (idPoste, label, idDepartement) values (741, 'Staff Accountant III', 741);
insert into Poste (idPoste, label, idDepartement) values (742, 'Operator', 742);
insert into Poste (idPoste, label, idDepartement) values (743, 'Environmental Specialist', 743);
insert into Poste (idPoste, label, idDepartement) values (744, 'Project Manager', 744);
insert into Poste (idPoste, label, idDepartement) values (745, 'Sales Representative', 745);
insert into Poste (idPoste, label, idDepartement) values (746, 'Payment Adjustment Coordinator', 746);
insert into Poste (idPoste, label, idDepartement) values (747, 'VP Product Management', 747);
insert into Poste (idPoste, label, idDepartement) values (748, 'Research Assistant I', 748);
insert into Poste (idPoste, label, idDepartement) values (749, 'Senior Cost Accountant', 749);
insert into Poste (idPoste, label, idDepartement) values (750, 'Pharmacist', 750);
insert into Poste (idPoste, label, idDepartement) values (751, 'General Manager', 751);
insert into Poste (idPoste, label, idDepartement) values (752, 'Staff Accountant I', 752);
insert into Poste (idPoste, label, idDepartement) values (753, 'Technical Writer', 753);
insert into Poste (idPoste, label, idDepartement) values (754, 'Electrical Engineer', 754);
insert into Poste (idPoste, label, idDepartement) values (755, 'Safety Technician IV', 755);
insert into Poste (idPoste, label, idDepartement) values (756, 'Electrical Engineer', 756);
insert into Poste (idPoste, label, idDepartement) values (757, 'Account Coordinator', 757);
insert into Poste (idPoste, label, idDepartement) values (758, 'Software Test Engineer IV', 758);
insert into Poste (idPoste, label, idDepartement) values (759, 'Nuclear Power Engineer', 759);
insert into Poste (idPoste, label, idDepartement) values (760, 'Cost Accountant', 760);
insert into Poste (idPoste, label, idDepartement) values (761, 'Staff Scientist', 761);
insert into Poste (idPoste, label, idDepartement) values (762, 'Teacher', 762);
insert into Poste (idPoste, label, idDepartement) values (763, 'Research Associate', 763);
insert into Poste (idPoste, label, idDepartement) values (764, 'Nurse', 764);
insert into Poste (idPoste, label, idDepartement) values (765, 'Paralegal', 765);
insert into Poste (idPoste, label, idDepartement) values (766, 'Tax Accountant', 766);
insert into Poste (idPoste, label, idDepartement) values (767, 'Environmental Specialist', 767);
insert into Poste (idPoste, label, idDepartement) values (768, 'Actuary', 768);
insert into Poste (idPoste, label, idDepartement) values (769, 'Account Executive', 769);
insert into Poste (idPoste, label, idDepartement) values (770, 'Nuclear Power Engineer', 770);
insert into Poste (idPoste, label, idDepartement) values (771, 'Nurse Practicioner', 771);
insert into Poste (idPoste, label, idDepartement) values (772, 'Compensation Analyst', 772);
insert into Poste (idPoste, label, idDepartement) values (773, 'Mechanical Systems Engineer', 773);
insert into Poste (idPoste, label, idDepartement) values (774, 'Senior Cost Accountant', 774);
insert into Poste (idPoste, label, idDepartement) values (775, 'Environmental Tech', 775);
insert into Poste (idPoste, label, idDepartement) values (776, 'VP Product Management', 776);
insert into Poste (idPoste, label, idDepartement) values (777, 'Professor', 777);
insert into Poste (idPoste, label, idDepartement) values (778, 'Geologist II', 778);
insert into Poste (idPoste, label, idDepartement) values (779, 'Director of Sales', 779);
insert into Poste (idPoste, label, idDepartement) values (780, 'Chemical Engineer', 780);
insert into Poste (idPoste, label, idDepartement) values (781, 'Environmental Specialist', 781);
insert into Poste (idPoste, label, idDepartement) values (782, 'Research Assistant IV', 782);
insert into Poste (idPoste, label, idDepartement) values (783, 'Recruiting Manager', 783);
insert into Poste (idPoste, label, idDepartement) values (784, 'Dental Hygienist', 784);
insert into Poste (idPoste, label, idDepartement) values (785, 'Senior Quality Engineer', 785);
insert into Poste (idPoste, label, idDepartement) values (786, 'Analog Circuit Design manager', 786);
insert into Poste (idPoste, label, idDepartement) values (787, 'Operator', 787);
insert into Poste (idPoste, label, idDepartement) values (788, 'Electrical Engineer', 788);
insert into Poste (idPoste, label, idDepartement) values (789, 'Nurse Practicioner', 789);
insert into Poste (idPoste, label, idDepartement) values (790, 'Help Desk Operator', 790);
insert into Poste (idPoste, label, idDepartement) values (791, 'Marketing Assistant', 791);
insert into Poste (idPoste, label, idDepartement) values (792, 'Community Outreach Specialist', 792);
insert into Poste (idPoste, label, idDepartement) values (793, 'Electrical Engineer', 793);
insert into Poste (idPoste, label, idDepartement) values (794, 'Senior Editor', 794);
insert into Poste (idPoste, label, idDepartement) values (795, 'Sales Representative', 795);
insert into Poste (idPoste, label, idDepartement) values (796, 'Engineer II', 796);
insert into Poste (idPoste, label, idDepartement) values (797, 'Compensation Analyst', 797);
insert into Poste (idPoste, label, idDepartement) values (798, 'Product Engineer', 798);
insert into Poste (idPoste, label, idDepartement) values (799, 'Analyst Programmer', 799);
insert into Poste (idPoste, label, idDepartement) values (800, 'Analog Circuit Design manager', 800);
insert into Poste (idPoste, label, idDepartement) values (801, 'Mechanical Systems Engineer', 801);
insert into Poste (idPoste, label, idDepartement) values (802, 'Recruiting Manager', 802);
insert into Poste (idPoste, label, idDepartement) values (803, 'Senior Sales Associate', 803);
insert into Poste (idPoste, label, idDepartement) values (804, 'Senior Financial Analyst', 804);
insert into Poste (idPoste, label, idDepartement) values (805, 'Assistant Professor', 805);
insert into Poste (idPoste, label, idDepartement) values (806, 'Web Designer II', 806);
insert into Poste (idPoste, label, idDepartement) values (807, 'Senior Developer', 807);
insert into Poste (idPoste, label, idDepartement) values (808, 'Junior Executive', 808);
insert into Poste (idPoste, label, idDepartement) values (809, 'Electrical Engineer', 809);
insert into Poste (idPoste, label, idDepartement) values (810, 'Human Resources Assistant III', 810);
insert into Poste (idPoste, label, idDepartement) values (811, 'Research Nurse', 811);
insert into Poste (idPoste, label, idDepartement) values (812, 'Speech Pathologist', 812);
insert into Poste (idPoste, label, idDepartement) values (813, 'Speech Pathologist', 813);
insert into Poste (idPoste, label, idDepartement) values (814, 'Senior Sales Associate', 814);
insert into Poste (idPoste, label, idDepartement) values (815, 'Software Consultant', 815);
insert into Poste (idPoste, label, idDepartement) values (816, 'VP Quality Control', 816);
insert into Poste (idPoste, label, idDepartement) values (817, 'Environmental Tech', 817);
insert into Poste (idPoste, label, idDepartement) values (818, 'Safety Technician IV', 818);
insert into Poste (idPoste, label, idDepartement) values (819, 'Assistant Media Planner', 819);
insert into Poste (idPoste, label, idDepartement) values (820, 'Media Manager II', 820);
insert into Poste (idPoste, label, idDepartement) values (821, 'Research Nurse', 821);
insert into Poste (idPoste, label, idDepartement) values (822, 'Business Systems Development Analyst', 822);
insert into Poste (idPoste, label, idDepartement) values (823, 'Senior Editor', 823);
insert into Poste (idPoste, label, idDepartement) values (824, 'Editor', 824);
insert into Poste (idPoste, label, idDepartement) values (825, 'Sales Associate', 825);
insert into Poste (idPoste, label, idDepartement) values (826, 'Human Resources Assistant IV', 826);
insert into Poste (idPoste, label, idDepartement) values (827, 'Sales Representative', 827);
insert into Poste (idPoste, label, idDepartement) values (828, 'Office Assistant II', 828);
insert into Poste (idPoste, label, idDepartement) values (829, 'Project Manager', 829);
insert into Poste (idPoste, label, idDepartement) values (830, 'Mechanical Systems Engineer', 830);
insert into Poste (idPoste, label, idDepartement) values (831, 'Staff Scientist', 831);
insert into Poste (idPoste, label, idDepartement) values (832, 'Biostatistician III', 832);
insert into Poste (idPoste, label, idDepartement) values (833, 'Systems Administrator IV', 833);
insert into Poste (idPoste, label, idDepartement) values (834, 'Senior Developer', 834);
insert into Poste (idPoste, label, idDepartement) values (835, 'Assistant Media Planner', 835);
insert into Poste (idPoste, label, idDepartement) values (836, 'Mechanical Systems Engineer', 836);
insert into Poste (idPoste, label, idDepartement) values (837, 'Executive Secretary', 837);
insert into Poste (idPoste, label, idDepartement) values (838, 'Structural Analysis Engineer', 838);
insert into Poste (idPoste, label, idDepartement) values (839, 'Geological Engineer', 839);
insert into Poste (idPoste, label, idDepartement) values (840, 'Associate Professor', 840);
insert into Poste (idPoste, label, idDepartement) values (841, 'Sales Representative', 841);
insert into Poste (idPoste, label, idDepartement) values (842, 'GIS Technical Architect', 842);
insert into Poste (idPoste, label, idDepartement) values (843, 'Chief Design Engineer', 843);
insert into Poste (idPoste, label, idDepartement) values (844, 'Database Administrator II', 844);
insert into Poste (idPoste, label, idDepartement) values (845, 'Operator', 845);
insert into Poste (idPoste, label, idDepartement) values (846, 'Assistant Professor', 846);
insert into Poste (idPoste, label, idDepartement) values (847, 'Senior Cost Accountant', 847);
insert into Poste (idPoste, label, idDepartement) values (848, 'Statistician II', 848);
insert into Poste (idPoste, label, idDepartement) values (849, 'Safety Technician I', 849);
insert into Poste (idPoste, label, idDepartement) values (850, 'Structural Analysis Engineer', 850);
insert into Poste (idPoste, label, idDepartement) values (851, 'Actuary', 851);
insert into Poste (idPoste, label, idDepartement) values (852, 'Professor', 852);
insert into Poste (idPoste, label, idDepartement) values (853, 'Assistant Media Planner', 853);
insert into Poste (idPoste, label, idDepartement) values (854, 'Engineer IV', 854);
insert into Poste (idPoste, label, idDepartement) values (855, 'Food Chemist', 855);
insert into Poste (idPoste, label, idDepartement) values (856, 'Financial Analyst', 856);
insert into Poste (idPoste, label, idDepartement) values (857, 'Editor', 857);
insert into Poste (idPoste, label, idDepartement) values (858, 'Design Engineer', 858);
insert into Poste (idPoste, label, idDepartement) values (859, 'Data Coordiator', 859);
insert into Poste (idPoste, label, idDepartement) values (860, 'Research Assistant IV', 860);
insert into Poste (idPoste, label, idDepartement) values (861, 'Quality Control Specialist', 861);
insert into Poste (idPoste, label, idDepartement) values (862, 'Design Engineer', 862);
insert into Poste (idPoste, label, idDepartement) values (863, 'Actuary', 863);
insert into Poste (idPoste, label, idDepartement) values (864, 'Human Resources Assistant I', 864);
insert into Poste (idPoste, label, idDepartement) values (865, 'Cost Accountant', 865);
insert into Poste (idPoste, label, idDepartement) values (866, 'Civil Engineer', 866);
insert into Poste (idPoste, label, idDepartement) values (867, 'Information Systems Manager', 867);
insert into Poste (idPoste, label, idDepartement) values (868, 'Human Resources Assistant III', 868);
insert into Poste (idPoste, label, idDepartement) values (869, 'Nuclear Power Engineer', 869);
insert into Poste (idPoste, label, idDepartement) values (870, 'Analyst Programmer', 870);
insert into Poste (idPoste, label, idDepartement) values (871, 'Cost Accountant', 871);
insert into Poste (idPoste, label, idDepartement) values (872, 'Internal Auditor', 872);
insert into Poste (idPoste, label, idDepartement) values (873, 'Environmental Specialist', 873);
insert into Poste (idPoste, label, idDepartement) values (874, 'Statistician I', 874);
insert into Poste (idPoste, label, idDepartement) values (875, 'Senior Financial Analyst', 875);
insert into Poste (idPoste, label, idDepartement) values (876, 'Editor', 876);
insert into Poste (idPoste, label, idDepartement) values (877, 'Senior Developer', 877);
insert into Poste (idPoste, label, idDepartement) values (878, 'Office Assistant II', 878);
insert into Poste (idPoste, label, idDepartement) values (879, 'Quality Control Specialist', 879);
insert into Poste (idPoste, label, idDepartement) values (880, 'Software Engineer I', 880);
insert into Poste (idPoste, label, idDepartement) values (881, 'Analog Circuit Design manager', 881);
insert into Poste (idPoste, label, idDepartement) values (882, 'Cost Accountant', 882);
insert into Poste (idPoste, label, idDepartement) values (883, 'Compensation Analyst', 883);
insert into Poste (idPoste, label, idDepartement) values (884, 'Business Systems Development Analyst', 884);
insert into Poste (idPoste, label, idDepartement) values (885, 'Technical Writer', 885);
insert into Poste (idPoste, label, idDepartement) values (886, 'Web Designer IV', 886);
insert into Poste (idPoste, label, idDepartement) values (887, 'Statistician I', 887);
insert into Poste (idPoste, label, idDepartement) values (888, 'VP Product Management', 888);
insert into Poste (idPoste, label, idDepartement) values (889, 'Geologist III', 889);
insert into Poste (idPoste, label, idDepartement) values (890, 'Data Coordiator', 890);
insert into Poste (idPoste, label, idDepartement) values (891, 'Research Associate', 891);
insert into Poste (idPoste, label, idDepartement) values (892, 'Budget/Accounting Analyst I', 892);
insert into Poste (idPoste, label, idDepartement) values (893, 'Sales Associate', 893);
insert into Poste (idPoste, label, idDepartement) values (894, 'Physical Therapy Assistant', 894);
insert into Poste (idPoste, label, idDepartement) values (895, 'Senior Editor', 895);
insert into Poste (idPoste, label, idDepartement) values (896, 'Nurse', 896);
insert into Poste (idPoste, label, idDepartement) values (897, 'Tax Accountant', 897);
insert into Poste (idPoste, label, idDepartement) values (898, 'Quality Engineer', 898);
insert into Poste (idPoste, label, idDepartement) values (899, 'Food Chemist', 899);
insert into Poste (idPoste, label, idDepartement) values (900, 'Editor', 900);
insert into Poste (idPoste, label, idDepartement) values (901, 'Junior Executive', 901);
insert into Poste (idPoste, label, idDepartement) values (902, 'Software Engineer I', 902);
insert into Poste (idPoste, label, idDepartement) values (903, 'Structural Analysis Engineer', 903);
insert into Poste (idPoste, label, idDepartement) values (904, 'Chief Design Engineer', 904);
insert into Poste (idPoste, label, idDepartement) values (905, 'Analyst Programmer', 905);
insert into Poste (idPoste, label, idDepartement) values (906, 'Database Administrator I', 906);
insert into Poste (idPoste, label, idDepartement) values (907, 'Accountant III', 907);
insert into Poste (idPoste, label, idDepartement) values (908, 'Librarian', 908);
insert into Poste (idPoste, label, idDepartement) values (909, 'Safety Technician II', 909);
insert into Poste (idPoste, label, idDepartement) values (910, 'Help Desk Technician', 910);
insert into Poste (idPoste, label, idDepartement) values (911, 'Design Engineer', 911);
insert into Poste (idPoste, label, idDepartement) values (912, 'Marketing Manager', 912);
insert into Poste (idPoste, label, idDepartement) values (913, 'Automation Specialist III', 913);
insert into Poste (idPoste, label, idDepartement) values (914, 'VP Sales', 914);
insert into Poste (idPoste, label, idDepartement) values (915, 'Quality Control Specialist', 915);
insert into Poste (idPoste, label, idDepartement) values (916, 'Financial Advisor', 916);
insert into Poste (idPoste, label, idDepartement) values (917, 'Professor', 917);
insert into Poste (idPoste, label, idDepartement) values (918, 'VP Quality Control', 918);
insert into Poste (idPoste, label, idDepartement) values (919, 'Marketing Manager', 919);
insert into Poste (idPoste, label, idDepartement) values (920, 'Internal Auditor', 920);
insert into Poste (idPoste, label, idDepartement) values (921, 'Teacher', 921);
insert into Poste (idPoste, label, idDepartement) values (922, 'Financial Advisor', 922);
insert into Poste (idPoste, label, idDepartement) values (923, 'Technical Writer', 923);
insert into Poste (idPoste, label, idDepartement) values (924, 'Health Coach I', 924);
insert into Poste (idPoste, label, idDepartement) values (925, 'Director of Sales', 925);
insert into Poste (idPoste, label, idDepartement) values (926, 'Junior Executive', 926);
insert into Poste (idPoste, label, idDepartement) values (927, 'Structural Analysis Engineer', 927);
insert into Poste (idPoste, label, idDepartement) values (928, 'VP Marketing', 928);
insert into Poste (idPoste, label, idDepartement) values (929, 'Automation Specialist III', 929);
insert into Poste (idPoste, label, idDepartement) values (930, 'Assistant Manager', 930);
insert into Poste (idPoste, label, idDepartement) values (931, 'Internal Auditor', 931);
insert into Poste (idPoste, label, idDepartement) values (932, 'Information Systems Manager', 932);
insert into Poste (idPoste, label, idDepartement) values (933, 'Analog Circuit Design manager', 933);
insert into Poste (idPoste, label, idDepartement) values (934, 'Marketing Assistant', 934);
insert into Poste (idPoste, label, idDepartement) values (935, 'Data Coordiator', 935);
insert into Poste (idPoste, label, idDepartement) values (936, 'Web Designer III', 936);
insert into Poste (idPoste, label, idDepartement) values (937, 'Data Coordiator', 937);
insert into Poste (idPoste, label, idDepartement) values (938, 'Engineer III', 938);
insert into Poste (idPoste, label, idDepartement) values (939, 'Nuclear Power Engineer', 939);
insert into Poste (idPoste, label, idDepartement) values (940, 'Administrative Officer', 940);
insert into Poste (idPoste, label, idDepartement) values (941, 'Data Coordiator', 941);
insert into Poste (idPoste, label, idDepartement) values (942, 'Staff Scientist', 942);
insert into Poste (idPoste, label, idDepartement) values (943, 'Account Executive', 943);
insert into Poste (idPoste, label, idDepartement) values (944, 'Research Associate', 944);
insert into Poste (idPoste, label, idDepartement) values (945, 'Structural Analysis Engineer', 945);
insert into Poste (idPoste, label, idDepartement) values (946, 'Help Desk Operator', 946);
insert into Poste (idPoste, label, idDepartement) values (947, 'Research Nurse', 947);
insert into Poste (idPoste, label, idDepartement) values (948, 'GIS Technical Architect', 948);
insert into Poste (idPoste, label, idDepartement) values (949, 'Cost Accountant', 949);
insert into Poste (idPoste, label, idDepartement) values (950, 'Executive Secretary', 950);
insert into Poste (idPoste, label, idDepartement) values (951, 'Information Systems Manager', 951);
insert into Poste (idPoste, label, idDepartement) values (952, 'Desktop Support Technician', 952);
insert into Poste (idPoste, label, idDepartement) values (953, 'Environmental Tech', 953);
insert into Poste (idPoste, label, idDepartement) values (954, 'Graphic Designer', 954);
insert into Poste (idPoste, label, idDepartement) values (955, 'Analog Circuit Design manager', 955);
insert into Poste (idPoste, label, idDepartement) values (956, 'Product Engineer', 956);
insert into Poste (idPoste, label, idDepartement) values (957, 'Product Engineer', 957);
insert into Poste (idPoste, label, idDepartement) values (958, 'Analyst Programmer', 958);
insert into Poste (idPoste, label, idDepartement) values (959, 'VP Accounting', 959);
insert into Poste (idPoste, label, idDepartement) values (960, 'Systems Administrator II', 960);
insert into Poste (idPoste, label, idDepartement) values (961, 'Structural Engineer', 961);
insert into Poste (idPoste, label, idDepartement) values (962, 'Staff Accountant IV', 962);
insert into Poste (idPoste, label, idDepartement) values (963, 'Account Coordinator', 963);
insert into Poste (idPoste, label, idDepartement) values (964, 'Food Chemist', 964);
insert into Poste (idPoste, label, idDepartement) values (965, 'Graphic Designer', 965);
insert into Poste (idPoste, label, idDepartement) values (966, 'Paralegal', 966);
insert into Poste (idPoste, label, idDepartement) values (967, 'Assistant Manager', 967);
insert into Poste (idPoste, label, idDepartement) values (968, 'Geologist I', 968);
insert into Poste (idPoste, label, idDepartement) values (969, 'Design Engineer', 969);
insert into Poste (idPoste, label, idDepartement) values (970, 'Associate Professor', 970);
insert into Poste (idPoste, label, idDepartement) values (971, 'Marketing Assistant', 971);
insert into Poste (idPoste, label, idDepartement) values (972, 'Web Developer II', 972);
insert into Poste (idPoste, label, idDepartement) values (973, 'Human Resources Assistant IV', 973);
insert into Poste (idPoste, label, idDepartement) values (974, 'Help Desk Operator', 974);
insert into Poste (idPoste, label, idDepartement) values (975, 'Recruiting Manager', 975);
insert into Poste (idPoste, label, idDepartement) values (976, 'Systems Administrator III', 976);
insert into Poste (idPoste, label, idDepartement) values (977, 'Mechanical Systems Engineer', 977);
insert into Poste (idPoste, label, idDepartement) values (978, 'Dental Hygienist', 978);
insert into Poste (idPoste, label, idDepartement) values (979, 'Social Worker', 979);
insert into Poste (idPoste, label, idDepartement) values (980, 'Senior Sales Associate', 980);
insert into Poste (idPoste, label, idDepartement) values (981, 'Statistician IV', 981);
insert into Poste (idPoste, label, idDepartement) values (982, 'Engineer IV', 982);
insert into Poste (idPoste, label, idDepartement) values (983, 'VP Marketing', 983);
insert into Poste (idPoste, label, idDepartement) values (984, 'Administrative Officer', 984);
insert into Poste (idPoste, label, idDepartement) values (985, 'Legal Assistant', 985);
insert into Poste (idPoste, label, idDepartement) values (986, 'Chemical Engineer', 986);
insert into Poste (idPoste, label, idDepartement) values (987, 'Quality Control Specialist', 987);
insert into Poste (idPoste, label, idDepartement) values (988, 'Safety Technician IV', 988);
insert into Poste (idPoste, label, idDepartement) values (989, 'Assistant Professor', 989);
insert into Poste (idPoste, label, idDepartement) values (990, 'Electrical Engineer', 990);
insert into Poste (idPoste, label, idDepartement) values (991, 'Data Coordiator', 991);
insert into Poste (idPoste, label, idDepartement) values (992, 'Nuclear Power Engineer', 992);
insert into Poste (idPoste, label, idDepartement) values (993, 'Computer Systems Analyst I', 993);
insert into Poste (idPoste, label, idDepartement) values (994, 'Senior Sales Associate', 994);
insert into Poste (idPoste, label, idDepartement) values (995, 'Editor', 995);
insert into Poste (idPoste, label, idDepartement) values (996, 'Geologist III', 996);
insert into Poste (idPoste, label, idDepartement) values (997, 'Environmental Tech', 997);
insert into Poste (idPoste, label, idDepartement) values (998, 'Information Systems Manager', 998);
insert into Poste (idPoste, label, idDepartement) values (999, 'Cost Accountant', 999);
insert into Poste (idPoste, label, idDepartement) values (1000, 'Teacher', 1000);
